import './Footer.css';
import './Foreword.css';
import './Header.css';
import './Info.css';
import './SlidedNav.css';
import './Slider.css';
import './ToDoList.css';
import './NavBar.css';
import './Passport.css';
import './Book.css';
import * as css from './Gallery/index';